data_path: "data/wordnet/trans"

pretrained: "all-MiniLM-L6-v2"

train:
  training_mode: bigger_ball
  train_trans_portion: 0.0
  num_epochs: 5
  learning_rate: 1e-5
  warmup_steps: 500
  train_batch_size: 256
  eval_batch_size: 1024
  loss:
    cluster:
      weight: 1.0
      min_distance: 0.1
      margin: 1.0
    centri:
      weight: 1.0
      margin: 0.1
    cone:  # cone loss is only applicable for smaller_cube (unit Poincare ball)
      weight: 0.0
      min_euclidean_norm: 0.1
      margin: 0.1
