# dataset from Hugging Face
dataset_path: "Hierarchy-Transformers/WordNetNoun"
dataset_name: "MixedHop-RandomNegatives"

# pre-trained model from Hugging Face
model_path: "sentence-transformers/all-MiniLM-L12-v2"

# training config
num_train_epochs: 3
train_batch_size: 256
eval_batch_size: 512
learning_rate: 1e-5 
