# local dataset downloaded from Zenodo
dataset_path: "data/wordnet-multi"
negative_type: "random"

# training config (on hyperbolic distance loss)
embed_dim: 200
num_train_epochs: 200
train_batch_size: 256
eval_batch_size: 512
learning_rate: 0.01
warmup_epochs: 10

# post-training config (on hyperbolic entailment cone loss)
num_post_train_epochs: 200  